import { type RouteConfig, index, route } from '@react-router/dev/routes';

export default [
  index('routes/landing.tsx'),
  route('planos', 'routes/pricing.tsx'),
  route('login', 'routes/login.tsx'),
  route('forgot-password', 'routes/forgot-password.tsx'),
  route('reset-password', 'routes/reset-password.tsx'),
  route('sistema', 'routes/home.tsx'),
  route('sistema/cadastros/propriedades', 'routes/register/property/Property.tsx'),
  route('sistema/cadastros/propriedades/novo', 'routes/register/property/NewProperty.tsx'),
  route('sistema/cadastros/propriedades/:id', 'routes/register/property/$id.tsx'),
  route('sistema/cadastros/propriedades/:id/editar', 'routes/register/property/editar.$id.tsx'),
  route('sistema/cadastros/localizacoes', 'routes/register/location/Location.tsx'),
  route('sistema/cadastros/localizacoes/novo', 'routes/register/location/NewLocation.tsx'),
  route('sistema/cadastros/localizacoes/:id', 'routes/register/location/$id.tsx'),
  route('sistema/cadastros/localizacoes/:id/editar', 'routes/register/location/editar.$id.tsx'),
  route('sistema/cadastros/prestadores-servico', 'routes/register/service-provider/ServiceProvider.tsx'),
  route(
    'sistema/cadastros/prestadores-servico/novo',
    'routes/register/service-provider/NewServiceProvider.tsx',
  ),
  route('sistema/cadastros/prestadores-servico/:id', 'routes/register/service-provider/$id.tsx'),
  route(
    'sistema/cadastros/prestadores-servico/:id/editar',
    'routes/register/service-provider/editar.$id.tsx',
  ),
  route('sistema/cadastros/colaboradores', 'routes/register/employee/Employee.tsx'),
  route('sistema/cadastros/colaboradores/novo', 'routes/register/employee/NewEmployee.tsx'),
  route('sistema/cadastros/colaboradores/:id', 'routes/register/employee/$id.tsx'),
  route('sistema/cadastros/colaboradores/:id/editar', 'routes/register/employee/editar.$id.tsx'),
  route('sistema/cadastros/fornecedores', 'routes/register/supplier/Supplier.tsx'),
  route('sistema/cadastros/fornecedores/novo', 'routes/register/supplier/NewSupplier.tsx'),
  route('sistema/cadastros/fornecedores/:id', 'routes/register/supplier/$id.tsx'),
  route('sistema/cadastros/fornecedores/:id/editar', 'routes/register/supplier/editar.$id.tsx'),
  route('sistema/cadastros/compradores', 'routes/register/buyer/Buyer.tsx'),
  route('sistema/cadastros/compradores/novo', 'routes/register/buyer/NewBuyer.tsx'),
  route('sistema/cadastros/compradores/:id', 'routes/register/buyer/$id.tsx'),
  route('sistema/cadastros/compradores/:id/editar', 'routes/register/buyer/editar.$id.tsx'),
  route('sistema/cadastros/animais', 'routes/register/animal/Animal.tsx'),
  route('sistema/cadastros/animais/novo', 'routes/register/animal/NewAnimal.tsx'),
  route('sistema/cadastros/animais/:id', 'routes/register/animal/$id.tsx'),
  route('sistema/cadastros/animais/:id/editar', 'routes/register/animal/editar.$id.tsx'),
  // Catch-all route must be last
  route('*', 'routes/catch-all.tsx'),
] satisfies RouteConfig;
